BBlog/Controllers/SearchController.cs
using BBlog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace BBlog.Controllers
{
    public class SearchController : Controller
    {
        private readonly BBlogContext _context;

        public SearchController (BBlogContext context)
        {
            _context = context;
        }

        [Route("[controller]")]
        public async Task<IActionResult> Index(string searchString)
        {
            var blogs = from b in _context.Blog
                        select b;

            if (!String.IsNullOrEmpty(searchString))
            {
                blogs = blogs.Where(s => s.Title.Contains(searchString) || s.Body.Contains(searchString));
            }

            var blogCategoryVM = new BlogSelectViewModel();
            blogCategoryVM.blogs = await blogs.ToListAsync();

            return View(blogCategoryVM);
        }

        [Route("Archive")]
        public async Task<IActionResult> Archive(string monthyear)
        {
            var blogs = from b in _context.Blog
                        select b;

            if (!String.IsNullOrEmpty(monthyear))
            {
                blogs = blogs.Where(s => s.PostDate.ToString("MMM yyyy").Equals(monthyear));
            }

            var blogVM = new BlogSelectViewModel();
            blogVM.blogs = await blogs.ToListAsync();

            return View(blogVM);
        }
    }
}

BBlog/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.min.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" style="border: 1px solid beige;">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-left">
                    <img src="~/images/mqicon.png" class="logo"/>
                </a>
            </div>
            <div class="navbar-collapse collapse navbar-left">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Blog">Blog</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                </ul>
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <form class="navbar-form" asp-controller="Search" asp-action="Index" method="get">
                    <input type="text" class="form-control search-bar" name="searchString" placeholder="Search" />
                </form>
            </div>
        </div>
    </nav>
    @if (ViewBag.PageImage != null && !string.IsNullOrWhiteSpace(ViewBag.PageImage))
    {
        <header class=@ViewBag.Class style="background-image: url('@ViewBag.PageImage')">
            <div class="intro-body">
                <h1>@ViewBag.Page</h1>
            </div>
            <div class="intro-action">
                <i class="glyphicon glyphicon-chevron-down"></i>
            </div>
        </header>
    }
    else
    {
        <header class="post-header"></header>
    }
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12" id="sidebar">
                @Html.Partial("_Sidebar")
            </div>
            <div class="col-lg-9 col-md-9 col-sm-8 col-xs-12" id="mainContent">
                @RenderBody()
            </div>
        </div>
    </div>
    <footer>
        <p>&copy; 2017 - Mighty Q</p>
    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)

    <div id="fb-root"></div>
    <script> (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>

BBlog/Views/Shared/_Post.cshtml
@model BBlog.Models.Blog

<div>
    <article>
        <h2>@Model.Title</h2>
        <p class="subinfo">
            <i class="glyphicon glyphicon-calendar"></i>
            <span class="inline-space">@Model.PostDate.ToString("MMM dd, yyyy")</span>
            <i class="glyphicon glyphicon-folder-open"></i>
            <span class="inline-space"><em>@Model.Category</em></span>
            @if (Model.Tags != null)
            {
                <i class="glyphicon glyphicon-tags"></i>
                <span class="inline-space">@Model.Tags</span>
            }
        </p>
        <br />
        <div>
            @Html.Raw(Model.Body)
        </div>
    </article>
    <hr />
    <div class="share-buttons">
        <div style="font-size: 18px; font-family: 'trebuchet ms', geneva;">Share this article</div>
        <div class="btn-group btn-group-sm" role="group">
            <button type="button" class="btn btn-default"><img src="~/images/facebook.png" /></button>
            <button type="button" class="btn btn-default"><img src="~/images/linkedin.png" /></button>
            <button type="button" class="btn btn-default"><img src="~/images/gplus.png" /></button>
            <button type="button" class="btn btn-default"><img src="~/images/twitter.png" /></button>
        </div>
    </div>
</div>

BBlog/Views/Shared/_PostSummary.cshtml
@model BBlog.Models.Blog

<div class="postsum">
    <article>
        <h3>@Html.ActionLink(Model.Title, "Post", "Home", new { category = Model.Category, id = Model.Id })</h3>
        <p class="subinfo">
            <i class="glyphicon glyphicon-calendar"></i>
            <span class="inline-space">@Model.PostDate.ToString("MMM dd, yyyy")</span>
            <i class="glyphicon glyphicon-folder-open"></i>
            <span class="inline-space"><em>@Model.Category</em></span>
            @if (Model.Tags != null)
            {
                <i class="glyphicon glyphicon-tags"></i>
                <span class="inline-space">@Model.Tags</span>
            }
        </p>
        <br />
        <div>
            @Html.Raw(Model.GetSummary())
        </div>
    </article>
    <hr />
</div>

BBlog/Views/Shared/_SideBar.cshtml
<div class="sidebar">
    <img src="~/images/header.jpg" style="height: auto; max-width:100%; border-bottom: solid 6px #ffffff; border-top-left-radius: 4px; border-top-right-radius: 4px;" />
    <div style="max-width:100%; height: 200px; background-color: #fed1bb; z-index: 0; border-bottom-left-radius:4px; border-bottom-right-radius: 4px;">
        <div style="width: 80px; height: 80px; position: relative; margin: auto; top: -45px;">
            <img src="~/images/avatar.jpg" style="max-width: 100%; height: auto; border-radius: 50%; position: absolute;" />
        </div>
        <div style="text-align: center; position: relative; top: -30px;">
            <p><span style="font-family: Comic Sans MS, cursive, sans-serif; font-size: 16px; color: #714242;">Mengqiao Li</span></p>
        </div>
    </div>
    <hr />
    <div style="padding: 2%; background-color: #fed1bb; border-radius: 4px;">
        <h4 style="text-align: center;">Category</h4>
        <div class="ajaxcall">
            <a style="margin: 1px 0" class="form-control btn btn-default" href="@Url.Action("Blog", "Home", new { blogCategory = "Dev" })">Dev</a>
            <a style="margin: 1px 0" class="form-control btn btn-default" href="@Url.Action("Blog", "Home", new { blogCategory = "Game" })">Game</a>
            <a style="margin: 1px 0" class="form-control btn btn-default" href="@Url.Action("Blog", "Home", new { blogCategory = "Recipe" })">Recipe</a>
            <a style="margin: 1px 0" class="form-control btn btn-default" href="@Url.Action("Blog", "Home", new { blogCategory = "Roam" })">Roam</a>
        </div>
    </div>
    <hr />
    <div>
        <form asp-controller="Search" asp-action="Index" method="get">
            <div class="input-group">
                <input type="text" name="searchString" class="form-control" asp-controller="Search" asp-action="Index" placeholder="Search" />
                <span class="input-group-btn">
                    <button class="btn" type="submit">
                        <i class="glyphicon glyphicon-search"></i>
                    </button>
                </span>
            </div>
        </form>
    </div>
    <hr />
    <div style="padding: 2%; background-color: #fed1bb; border-radius: 4px;">
        <h4 style="text-align: center;">Archive</h4>
        <form asp-controller="Search" asp-action="Archive" method="get">
            <ul class="nav nav-pills nav-stacked">
                <li><button class="form-control" name="monthyear" type="submit" value="June 2017">June 2017</button></li>
                <li><button class="form-control" name="monthyear" type="submit" value="May 2017">May 2017</button></li>
                <li><button class="form-control" name="monthyear" type="submit" value="Apr 2017">April 2017</button></li>
                <li><button class="form-control" name="monthyear" type="submit" value="Mar 2017">March 2017</button></li>
            </ul>
        </form>
    </div>
    <hr />
</div>